name: Test All src Files

on: [push, pull_request]

jobs:
  setup_env:
    name: Test All Files
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile Files
        run : |
          git submodule init
          git submodule update
          mkdir build
          cd build/
          cmake ..
          make all

      - name: Run Unit Test
        run : |
          cd build/tests
          ./sauvc-thruster-lib_test

  style_lint:
    name: CppLint All Files
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cpplint
        run : |
          python -m pip install --upgrade pip
          sudo pip install cpplint
          export PATH=$PATH:~/.local/bin/
          ls -l /usr/local/bin/cpplint

      - name: Lint Files
        run : |
          cpplint ./tests/* ./src/*
