name: Test All src Files

on: 
  push:
    branches: [feat-imu-2nd-try]
  pull_request:
    branches: [feat-imu-2nd-try]

jobs:
  setup_env:
    name: Test All Files
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile Files
        run : |
          git submodule init
          git submodule update
          mkdir build
          cd build/
          cmake ..
          make all


      - name: Run Unit Test
        run : |
          ./tests/sauvc-thruster-lib_test

  style_lint:
    name: CppLint All Files
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cpplint
        run : |
          pip install --user cpplint
          export PATH=$PATH:~/.local/bin/

      - name: Lint Files
        run : |
          cpplint ./tests/* ./src/*








